### ISSUE TITLE
refactor: document driven

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/docs#64]
For Shadcn we first need to change the docs structure. Then we can code the shadcn page. For this, we need to [document driven](https://content.nuxtjs.org/guide/writing/document-driven)open and add pages to the primitives page and leave it in a way that it will still receive content text.

[Example docs](https://github.com/nuxt/ui/tree/dev/docs)

```
pages
 - primitives
   - [...slug].vue
   - index.vue
 - shadcn
   - [...slug].vue
   - index.vue
index.vue
about.vue
```

We need to establish this structure somehow. Because primitives are just one of our products
It will be better to folder projects with the nuxt 3 layer structure.

```
So we will have this in our nuxt layer
/oku
/primitives
/shacdn
core -> nuxt config extends [..oku, ...primitives] ....
```

**Comment by ejirocodes** [comment]
Hi @productdevbook, what files would be in  `oku` and `primitives` layers

**Comment by productdevbook** [comment]
@ejirocodes `oku` home page and about. `primivives` You can move all of them, including content and components, to your own area.
